name: Andrej Hoferica, FIIT STU
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "http://andrew141.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jemoji